name: web_support
channels:
- conda-forge
- defaults
dependencies:
- blinker=1.4=py_1
- flask-mail=0.9.1=py36_1
- click=6.7=py36_0
- flask=0.12.2=py36_0
- flask-wtf=0.14.2=py36_0
- jinja2=2.9.6=py36_0
- pip=9.0.1=py36_1
- python=3.6.2=0
- pyyaml=3.12=py36_0
- werkzeug=0.12.2=py36_0
- wheel=0.29.0=py36_0
- wtforms=2.1=py36_0
- pip:
  - setuptools=27.2.0
  - sqlite=3.13.0
  - xz=5.2.2
  - zlib=1.2.8
  - readline=6.2
  - tk=8.5.18
  - yaml=0.1.6
  - itsdangerous=0.24
  - markupsafe=0.23
  - openssl=1.0.2l

